sudo: required
language: node_js
cache: npm
branches:
  only:
    - master

script:
  - npm run build
  # nextjs moves generated assets into _next directory
  # which is ignored by gh-pages / jekyll
  # therefore disable jekyll (we have static html files anyway)
  - touch ./out/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: out
  target-branch: gh-pages
  keep-history: true
  project-name: Urlaubsverwaltung
  on:
    branch: master

env:
  global:
    - ASSET_PREFIX: "https://synyx.github.io/urlaubsverwaltung-landingpage/"
    - secure: pzrxCQ4w4VEQdgQAOLpI9qT0aSdt2hqIbavSageHgX69fpHAdoZH9GQgpMx6gXjb+Da+J3epj+hLEEUFae+Iwx65TvCAYcvtSymrkLtGrL8BYs8IhngzKzkMxSCj2Q7Lw1uvD1cc21HkrGl6thQaRSVXlf5rqkYKFeBI843xFuFBstf8hU38t2WLOB6l+QIIuwmUXs9/+cJGx7rKKh4bymVqK0p8btrnvLR331p4rqGshdMtTKe9GzSoVVR5aYUZjubHPgaQ/HG08bUvLItrzNpUsZHenu4nzBltetwHUYjPKbmWVCZclrwFhM3V4qA1ahsKDIkSvyGFR4JL4XxzoQc7Hpv4ToUktXbc7LOd/fiDuWPfAmwsksstygaedsAH2xj4U7GOO3SPU1MH3Yy4QOnb41KF6e8fNQ2IQoMZzT0ApjmhAUFxFM+RZaaistG00aP9oQAfCXmrq6iYEU3T5mxZGA/hhSZE0MU87UM2XcEDgEf7fJuJgBWu2aMgjbfMxfKPt6K7oJp8xk/j73yyeERUMlyqb/FJzgZlo7sA6uliWQ2DjtDx7JpTdXtVZO8GtcoLL5pzAc47gVBPpcnkM1w4Mh2CepeKVh+2OGanwX5At6XkAAYtwcplAr657TTR6Z0u+Fus1rP9q11CoGun0iN2DKXTM92Hz5eB0Dh2v7Q=
