name: Check a11y

on:
  schedule:
    - cron: "2 4 * * *"
  workflow_dispatch:

jobs:
  a11y:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: a11ywatch/github-action@v1.14.0
        with:
          WEBSITE_URL: https://urlaubsverwaltung.cloud
          SUBDOMAINS: true
          TLD: false
          SITEMAP: true
          FAIL_ERRORS_COUNT: 15
          LIST: true
          FIX: false
          UPGRADE: false
