name: Build and deploy github pages

on:
  schedule:
    - cron: "2 4 * * *"
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      - name: Build
        run: |
          npm ci
          npm run build
          touch ./dist/.nojekyll
          echo "urlaubsverwaltung.cloud" > ./dist/CNAME
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
