name: Mark issue as planned

on:
  issues: {types: milestoned}

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        name: Add label 'status planned' to issue when milestoned
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.addLabels({...context.issue, labels: ['status: planned']})
