name: Check Links (with external)

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  link-check-on-uv-cloud:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Check all links
        run: docker run --rm --network host ghcr.io/linkchecker/linkchecker:latest https://urlaubsverwaltung.cloud --check-extern --ignore-url=https://www.gesetze-im-internet.de
