name: Check Links (with external)

on:
  schedule:
    - cron: "2 2 * * *"
  workflow_dispatch:

jobs:
  link-check-on-uv-cloud:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Check all links
        run: docker run --rm --network host -v "./link-check-skip-file.txt:/skipfiles/link-check-skip-file.txt" tennox/linkcheck:3.0.0 https://urlaubsverwaltung.cloud -e --skip-file /skipfiles/link-check-skip-file.txt
