name: Check Links (with external)

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  link-check-on-uv-cloud:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Check all links
        run: docker run --rm --network host -v "./link-check-skip-file.txt:/skipfiles/link-check-skip-file.txt" tennox/linkcheck:3.0.0 https://urlaubsverwaltung.cloud -e --skip-file /skipfiles/link-check-skip-file.txt
